baseURL = "https://responsabil.uncommercial.org/"
title = "Responsabil"
languageCode = "ro"
defaultContentLanguage = "ro"
paginate = 10
enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = false

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  title = "Responsabil"
  description = "Sursa ta de știri despre securitate cibernetică în limba română. Află cum să te protejezi pe internet, sfaturi utile și noutăți IT pentru siguranța ta digitală în era AI."
  author = "Eugene Melnic"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowShareButtons = true
  ShareButtons = ["telegram", "facebook", "whatsapp", "x", "linkedin"]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.homeInfoParams]
    Title = "Responsabil"
    Content = "Sursa ta de știri despre securitate cibernetică în limba română. Află cum să te protejezi pe internet, sfaturi utile și noutăți IT pentru siguranța ta digitală în era AI."

  [params.profileMode]
    enabled = false

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/uncommercial-org/responsabil"

  [params.assets]
    disableHLJS = true

  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false

  [params.editPost]
    URL = "https://github.com/uncommercial-org/responsabil/blob/main/content"
    Text = "Sugerează modificări"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10
    keys = ["title", "permalink", "summary", "content"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

[[menus.main]]
  identifier = "blog"
  name = "Securitate cibernetică"
  url = "/posts/securitate"
  weight = 10

[[menus.main]]
  identifier = "noutati"
  name = "Viața Digitală"
  url = "/posts/digital_life"
  weight = 20

[[menus.main]]
  identifier = "about"
  name = "Despre"
  url = "/pages/about/"
  weight = 40

[[menus.main]]
  identifier = "search"
  name = "Căutare"
  url = "/search/"
  weight = 50
